name: main

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-checks:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10', '3.11']
        test-os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.test-os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: '**/requirements.txt'

      - name: Install test dependencies
        run: pip install -r script/requirements-dev.txt

      - name: Lint
        run: ./script/linting/lint

      - name: Typecheck
        run: ./script/typing/check

      - name: Test
        run: SHELL=$SHELL ./run-tests

  action-check:
    strategy:
      matrix:
        test-os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.test-os }}
    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Setup
        run: |
          echo foo > /tmp/foo.out
          echo bar > /tmp/bar.out

      - uses: ./.
        with:
          command: python -c "print('foo', file=open('/tmp/foo.out', mode='w')); print('bar', file=open('/tmp/bar.out', mode='w'))"
          files: |
            /tmp/foo.out
            /tmp/bar.out
